[project]
name = "langgraph-demo"
version = "0.1.0"
description = "LangGraph"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "langchain>=0.3.26",
    "langchain-google-genai>=2.1.8",
    "langgraph>=0.5.3",
    "notebook>=7.4.4",
]
